name: Compile
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Git (required by BuildTools)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      - name: Download BuildTools
        run: wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      
      # Java 8 for older versions
      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      
      - name: Install CraftBukkit 1.8.8, 1.12.2, 1.16.5
        run: |
          java -jar BuildTools.jar --rev 1.8.8 --compile craftbukkit
          java -jar BuildTools.jar --rev 1.12.2 --compile craftbukkit
          java -jar BuildTools.jar --rev 1.16.5 --compile craftbukkit
      
      # Java 17 for mid versions
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      
      - name: Install CraftBukkit 1.17.1, 1.18.2, 1.19.4, 1.20.1, 1.20.4
        run: |
          java -jar BuildTools.jar --rev 1.17.1 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.18.2 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.19.4 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.20.1 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.20.4 --compile craftbukkit --remapped
      
      # Java 21 for newest versions
      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      
      - name: Install CraftBukkit 1.20.6, 1.21, 1.21.1, 1.21.4, 1.21.5, 1.21.7, 1.21.9
        # Use build number 4287 to compile CraftBukkit 1.21
        # Use build number 4522 to compile CraftBukkit 1.21.7
        # https://hub.spigotmc.org/jira/browse/BUILDTOOLS-658
        # https://hub.spigotmc.org/versions/
        run: |
          java -jar BuildTools.jar --rev 1.20.6 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 4287 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.21.1 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.21.4 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.21.5 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 4522 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.21.9 --compile craftbukkit --remapped
      
      # Setup Java for Maven build with cache
      - name: Setup JDK 21 for Maven Build
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'maven'
      
      - name: Compile InvSee++
        run: mvn clean package install --batch-mode --update-snapshots
      
      - name: Create tagged release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            InvSee++_Plugin/target/InvSee++.jar
            InvSee++_Give_Plugin/target/InvSee++_Give.jar
            InvSee++_Clear_Plugin/target/InvSee++_Clear.jar
            InvSee++_Clone_Plugin/target/InvSee++_Clone.jar
      
      - name: Deploy Javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-distribution: temurin
          java-version: 25
          custom-command: 'mvn package javadoc:aggregate -pl :invsee-plus-plus,:invsee-plus-plus_plugin,:invsee-plus-plus_common'
          target-folder: javadoc
          project: maven
